### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by notshwuy** [sxhk0/phemera#2]
#### Main Scope

- [ ] add task expiration to the form.
- [ ] delete tasks when they expire.

#### Extra

- [ ] add styles to phemera.
